# Use root/example as user/password credentials
version: '3.1'
networks: 
  nanny:
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kindergarten
    networks:
     - nanny
  node:
    image: node:17-alpine3.15
    container_name: nodejs
    restart: always
    volumes: 
     - ./code:/var/www/code
    networks:
     - nanny
    ports:
      - '3333:3333'
    depends_on:
      - db
    command: npm run --prefix /var/www/code server

  # build-frontend:
  #   image: node:17-alpine3.15
  #   container_name: build-frontend
  #   volumes: 
  #    - ./code/frontend:/var/www/code
  #   networks:
  #    - nanny
  #   depends_on:
  #     - node
  #   command: npm run --prefix /var/www/code build

  # nginx:
  #   image: nginx:latest
  #   volumes: 
  #     - ./code/frontend:/var/www/code
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - build-frontend
  #   ports:
  #     - "80:80"'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
    networks:
     - nanny
